#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: false

# Configure Floating IP (Ubuntu 18.04 LTS)
write_files:
  - content: |
      auto eth0:1
      iface eth0:1 inet static
          address ${floating_ip}
          netmask 32
    path: /etc/network/interfaces.d/60-my-floating-ip.cfg

# Install required packages
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

# Install & Start Docker
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker

final_message: "The system is finally up, after $UPTIME seconds"
